---
title: |
    | ARIC Heart Failure Proteomics:
    | Analysis and Results
author: 'Pranav Dorbala'
email: 'pdorbala@bwh.harvard.edu'
bibliography: references.bib
date: "January 22nd, 2021"
link-citations: no
output: 
    pdf_document:
        template: jdf-template.pandoc
        fig_caption: true
        citation_package: biblatex
        keep_tex: true
vignette: >
  %\VignetteIndexEntry{aric-proteomics-hf}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
abstract: Placeholder
---

```{r setup, include = FALSE}

knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

options(rmarkdown.html_vignette.check_title = FALSE)
```

```{r libraries, message=FALSE, warning=FALSE}
source('../R/load-data.R')
source('../R/make-tables.R')
source('../R/temp-fig1.R')
source('../R/cox-array.R')
source('../R/elastic-net.R')
source('../R/random-forest.R')
source('../R/wgcna.R')
source('../R/linear-array.R')
source('../R/linear-elastic-net.R')
source('../R/linear-random-forest.R')

library(magrittr)

set.seed(101010)
doParallel::registerDoParallel(12)
future::plan(future::multisession, workers = 8)

```

```{r file.path.setup, message=FALSE, warning=FALSE}

path <- function(...) { 
  return(file.path('..', 'inst', 'extdata', ...))  
}

label.path <- path('study-data', 'proteinMapping.csv')
study.path <- path('study-data', 'ARICmaster_121820.dta')

soma5.path <- path('study-data', 'ARICsomaV5.txt')
soma3.path <- path('study-data', 'ARICsomaV3.txt')

mods5.path <- path('aux-data', 'visit-five')
mods3.path <- path('aux-data', 'visit-three')

addtl.vars <- path('study-data', 'ARIC_newvar_010621.dta')
addtl.mods <- path('aux-data', 'visit-five', 'adtlvars.csv')
echov.mods <- path('aux-data', 'visit-five', 'echovars.csv')

```

```{r data.load, echo=TRUE, message=FALSE, warning=FALSE}

labels <-
  get.labels(label.path, sid,
             uniprot.full.name,
             entrezgenesymbol,
             flag2 == 0)

adjust.vars <- 
  readr::read_csv(file.path(mods5.path, 
                            'adjusted.csv'))

aric.master <- 
  haven::read_dta(study.path)

soma.data.5 <-
  get.soma(soma5.path, labels = labels)

soma.data.3 <-
  get.soma(soma3.path, labels = labels)

proteins <- labels$term
time <- "fuptime"
outc <- "hfdiag"

adjust <- adjust.vars$Variable[-1]
vars <- c(proteins, adjust, time, outc)

```

```{r v5.data.processing, message=FALSE, warning=FALSE}

visit.five <- 
  get.visit(soma.data = soma.data.5,
            path.mods = mods5.path,
            master = aric.master)

table1 <- 
  make.tables(visit.five, 
              time, outc, 
              path('aux-data', 
                   'table-template.csv'))

res <- 
  consort('.', mods5.path, soma.data.5, 
          visit.five, labels, time, outc)

```

```{r v3.data.processing, message=FALSE, warning=FALSE}

visit.three <- 
  get.visit(soma.data = soma.data.3,
            path.mods = mods3.path,
            master = aric.master)

table2 <- 
  make.tables(visit.three,
              time, outc,
              path('aux-data',
                   'table-template.csv'))

res2 <- 
  consort('.', mods3.path, soma.data.3, 
          visit.three, labels, time, outc)

```

```{r v5.consort fig.height=6, echo=FALSE}
res
```

```{r v5.table1, echo=FALSE}
knitr::kable(table1)
```

```{r v3.consort, fig.height=6 echo=FALSE}
res2
```

```{r v3.table1, echo=FALSE}
knitr::kable(table2)
```

```{r visit.data.scaling}

num.var <- numeric.id(visit.five, adjust)

fifth.visit <- visit.five  %>%
  get.scaled(num.var, proteins)

third.visit <- visit.three %>%
  get.scaled(num.var, proteins)

```


```{r visit.five.uniprotein}

fifth <- fifth.visit %>% 
  dplyr::select(dplyr::all_of(vars))

univariate.results <-
  cox.arry(proteins, fifth, 
           time, outc, adjust, 1)

```

```{r visit.five.uniprotein.refpef}

# fifth.ref <- fifth.visit %>% 
#   dplyr::select(dplyr::all_of(c(proteins, adjust, time, 'hfpef')))
# 
# fifth.pef <- fifth.visit %>% 
#   dplyr::select(dplyr::all_of(c(proteins, adjust, time, 'hfref')))
# 
# univariate.results.ref <-
#   cox.arry(proteins, fifth.ref, 
#            time, 'hfpef', adjust, 1)
# 
# univariate.results.pef <-
#   cox.arry(proteins, fifth.pef, 
#            time, 'hfref', adjust, 2)
# 
# plot.data.refpef <-
#   dplyr::bind_rows(univariate.results.ref,
#                    univariate.results.pef) %>%
#   dplyr::mutate(Name = labels[term, "name"])
# 
# bonferroni.ref <- 
#   terms.to.keep(plot.data.refpef,
#                 .pval = 0.05/length(proteins), 1)
# 
# 
# bf.visit.five.ref <- bonferroni.ref$data %>% 
#   dplyr::filter(src == 1) %>% 
#   dplyr::arrange(pval) %>%
#   dplyr::left_join(univariate.results.pef %>% 
#                      dplyr::select(term, desc),
#                    by = "term",
#                    suffix = c(".pEF", ".rEF")) %>%
#   dplyr::mutate(Name = substr(Name, 1, 25)) %>%
#   dplyr::select(term, Name, desc.pEF, desc.rEF, )
# 
# names(bf.visit.five.ref) <- c("SeqId", "Name", "HR Visit 5 pEF", "HR Visit 5 rEF")
# 
# bf.visit.five.ref %>% write.csv('~/Desktop/pef.csv', row.names=F)
# # 
# 
# plot.data.visit.five.refpef <- 
#   dplyr::left_join(univariate.results.ref,
#                    univariate.results.pef,
#                    by = "term",
#                    suffix = c(".pEF", ".rEF")) %>%
#   dplyr::mutate(Name = substr(labels[term, 'name'], 1, 25))
# 
# volcanoPlot.temp(plot.data.visit.five.refpef, 
#             length(proteins),
#             length(proteins),
#             suffix = c(".rEF", ".pEF"), 
#             title = "ARIC Visit 5 Incident HFpEF (pEF HR on x-axis)",
#             subtitle = "Color = rEF Significance, Shape = pEF Significance") 
# 
```


```{r beta.beta}
# 
# pdv5 <- plot.data.visit.five.refpef %>%
#   dplyr::mutate(pv1 = cut(pval.rEF, breaks = c(0, 0.05/4877, 0.05, 1), labels = c("royalblue", "red2", "grey30")),
#                 pv1 = as.character(pv1),
#                 pv2 = cut(pval.pEF, breaks = c(0, 0.05/4877, 0.05, 1), labels = c(17, 20, 4)),
#                 pv2 = as.numeric(levels(pv2))[pv2]) %>%
#   dplyr::group_by(pv1, pv2) %>%
#   dplyr::group_split()
# 
# par(pty = "s")
# j <- rep(c(rgb(76/255, 76/255, 76/255, 0.1), rgb(238/255,0,0, 0.2), rgb(0, 35/255, 102/255, 0.6)), each = 3)
# 
# for (i in 1:length(pdv5)) {
#   print(j[i])
#   plot(log(pdv5[[i]]$hazr.rEF), log(pdv5[[i]]$hazr.pEF), col = j[i], pch = pdv5[[i]]$pv2[1],
#        xlim = c(-0.5, 0.75),
#        ylim = c(-0.5, 0.75),
#        xlab = "",
#        ylab = "",
#        asp = 1)
#   par(new = T)
# }
# title(main = "Beta vs Beta Visit 5 rEF vs Visit 5 pEF",
#       xlab = "Visit 5 rEF Beta",
#       ylab = "Visit 5 pEF Beta")
# 
# abline(h=0, lty=c(2), col = c("black"))
# abline(v=0, lty=c(2), col = c("black"))
# abline(a=0, b=1, lty=c(2), col = c("black"))
# 

```


```{r visit.three.uniprotein}

third <- third.visit %>% 
  dplyr::select(dplyr::all_of(vars))

validation.results <- 
  cox.arry(proteins, third, 
           time, outc,  adjust, 2)
```

```{r replication.analysis.univariate}

plot.data <-
  dplyr::bind_rows(univariate.results,
                   validation.results) %>%
  dplyr::mutate(Name = labels[term, "name"])

bonferroni <- 
  terms.to.keep(plot.data,
                .pval = 0.05/length(proteins), 1)
falsediscr <- 
  terms.to.keep(plot.data, 
                .pval = 0.05, 1)

retained <-
  terms.to.keep(plot.data, 
                .pval = 0.05, 2, 
                .terms = bonferroni$kept)

retained2 <-
  terms.to.keep(plot.data, 
                .pval = 0.05/length(bonferroni$kept), 2, 
                .terms = bonferroni$kept)
```

```{r num.repl.proteins}

"<=== Sig at BF Visit 5 ===> Proteins: " %>%
  paste0(length(bonferroni$kept)) %>%
  print()

"<=== Sig at BF Visit 5 " %>% 
  paste0("FDR Visit 3 ===> Proteins: ",
         length(retained$kept)) %>%
  print()

"<=== Sig at FDR Visit 5 ===> Proteins: " %>%
  paste0(length(falsediscr$kept)) %>%
  print()

```

```{r univariate.data.export}

bf.visit.five <- bonferroni$data %>% 
  dplyr::filter(src == 1) %>% 
  dplyr::arrange(pval) %>%
  dplyr::left_join(validation.results %>% 
                     dplyr::select(term, desc),
                   by = "term",
                   suffix = c(".V5", ".V3")) %>%
  dplyr::mutate(r = dplyr::if_else(term %in% retained$kept, 
                                   "+", ""),
                Name = substr(Name, 1, 25)) %>%
  dplyr::select(term, Name, desc.V5, desc.V3, r)

names(bf.visit.five) <- c("SeqId", "Name", "HR Visit 5", "HR Visit 3", "Repl")


```


```{r uniprotein.volcano.plot}

plot.data.visit.five <- 
  dplyr::left_join(univariate.results,
                   validation.results,
                   by = "term",
                   suffix = c(".V5", ".V3")) %>%
  dplyr::mutate(Name = substr(labels[term, 'name'], 1, 25))

p <- volcanoPlot(plot.data.visit.five, 
            length(proteins),
            length(bonferroni$kept),
            suffix = c(".V5", ".V3"), 
            title = "ARIC Visit 5 Incident HF",
            subtitle = "Color = V5 Significance, Shape = V3 Significance") 

           

```


```{r elastic.net.survival}

fifth.lasso <- elastic.net(fifth.visit, 
                           bonferroni$kept, 
                           adjust, time, outc)

fifth.score <- get.score(fifth.visit, 
                         fifth.lasso$coefs, 
                         adjust, time, outc)

third.score <- get.score(third.visit, 
                         fifth.lasso$coefs, 
                         adjust, time, outc)

```

```{r randomForests.survival, cache=TRUE}

random.forest.list <- 
  filter.rf(fifth, time, outc, 30, adjust)

min.tree <- select.min.tree(random.forest.list)

third.visit.rf <- 
  predict.new.tree(third, min.tree$rand.tree, 
                   time, outc)

fifth.score.rf <- 
  rf.tree.score(fifth, min.tree$rand.tree,
                time, outc)

third.score.rf <- 
  rf.tree.score(third, third.visit.rf, 
                time, outc)

p <- plot.var.imp(min.tree$rand.tree, labels)

```

```{r weighted.gene}

wg.data <- fifth.visit %>%
  dplyr::select(dplyr::contains("SeqId"))

sft <- soft.threshold(wg.data)
clustered.tree <- hierTree(wg.data, sft)

```

```{r eigenGenes}

eigenGenes <- 
  calculate.eigengenes(wg.data, clustered.tree$dynCl)

plot.new.colors(clustered.tree$htree, 
                clustered.tree$dynCl, 
                eigenGenes$mergedColors,
                c("Old Colors", "New Colors"))

```

```{r module.summaries}

eigenData <- eigenGenes$mergedMEs %>%
  dplyr::mutate_all(scale, T, T) %>%
  dplyr::bind_cols(fifth.visit %>% 
    dplyr::select(dplyr::all_of(c(adjust, time, outc, "hfref", "hfpef"))))

eigenData.V3 <- calculate.eigengenes(third.visit %>% 
                                       dplyr::select(dplyr::contains("SeqId")),
                                     clustered.tree$dynCl)

eigenData.V31 <- eigenData.V3

eigenData.V3 <- eigenData.V31$mergedMEs %>%
  dplyr::mutate_all(scale, T, T) %>%
  dplyr::bind_cols(third.visit %>% 
    dplyr::select(dplyr::all_of(c(adjust, time, outc))))

mod.summary <- 
  summarize.modules(wg.data, 
                    eigenGenes$mergedColors,
                    sft, labels) %>%
  dplyr::mutate(color = paste0("ME", color))

module.incident.hf <- cox.arry(mod.summary$color,
                               eigenData, time, outc, 
                               adjust, .src = 1) %>%
  dplyr::left_join(mod.summary, by = c("term" = "color")) %>%
  dplyr::select(term, Name, desc, dplyr::everything())

module.incident.hf.V3 <- cox.arry(mod.summary$color,
                               eigenData.V3, time, outc, 
                               adjust, .src = 1) %>%
  dplyr::left_join(mod.summary, by = c("term" = "color")) %>%
  dplyr::select(term, Name, desc, dplyr::everything())

module.incident.ref <- cox.arry(mod.summary$color,
                               eigenData, time, "hfref", 
                               adjust, .src = 1) %>%
  dplyr::left_join(mod.summary, by = c("term" = "color")) %>%
  dplyr::select(term, Name, desc, dplyr::everything())


module.incident.pef <- cox.arry(mod.summary$color,
                               eigenData, time, "hfpef", 
                               adjust, .src = 1) %>%
  dplyr::left_join(mod.summary, by = c("term" = "color")) %>%
  dplyr::select(term, Name, desc, dplyr::everything())


module.incident.hf.unadj <- cox.arry(mod.summary$color,
                               eigenData, time, outc, 
                               adjust = NULL, .src = 1) %>%
  dplyr::left_join(mod.summary, by = c("term" = "color")) %>%
  dplyr::select(term, Name, desc, dplyr::everything())

module.incident.hf.V3.unadj <- cox.arry(mod.summary$color,
                               eigenData.V3, time, outc, 
                               adjust = NULL, .src = 1) %>%
  dplyr::left_join(mod.summary, by = c("term" = "color")) %>%
  dplyr::select(term, Name, desc, dplyr::everything())

module.incident.ref.unadj <- cox.arry(mod.summary$color,
                               eigenData, time, "hfref", 
                               adjust = NULL, .src = 1) %>%
  dplyr::left_join(mod.summary, by = c("term" = "color")) %>%
  dplyr::select(term, Name, desc, dplyr::everything())


module.incident.pef.unadj <- cox.arry(mod.summary$color,
                               eigenData, time, "hfpef", 
                               adjust = NULL, .src = 1) %>%
  dplyr::left_join(mod.summary, by = c("term" = "color")) %>%
  dplyr::select(term, Name, desc, dplyr::everything())


plot.module.inchf.adj <- 
  module.incident.hf %>% 
  dplyr::mutate(Color = substring(term, 3, 100)) %>%
  dplyr::select(Color, desc, hazr, pval, Name, hubs, freq)

plot.module.inchf.V3.adj <- 
  module.incident.hf.V3 %>% 
  dplyr::mutate(Color = substring(term, 3, 100)) %>%
  dplyr::select(Color, desc, hazr, pval, Name, hubs, freq)

plot.module.incref.adj <- 
  module.incident.ref %>% 
  dplyr::mutate(Color = substring(term, 3, 100)) %>%
  dplyr::select(Color, desc, hazr, pval, Name, hubs, freq)

plot.module.incpef.adj <- 
  module.incident.pef %>% 
  dplyr::mutate(Color = substring(term, 3, 100)) %>%
  dplyr::select(Color, desc, hazr, pval, Name, hubs, freq)

plot.module.inchf.unadj <- 
  module.incident.hf.unadj %>% 
  dplyr::mutate(Color = substring(term, 3, 100)) %>%
  dplyr::select(Color, desc, hazr, pval, Name, hubs, freq)

plot.module.inchf.V3.unadj <- 
  module.incident.hf.V3.unadj %>% 
  dplyr::mutate(Color = substring(term, 3, 100)) %>%
  dplyr::select(Color, desc, hazr, pval, Name, hubs, freq)

plot.module.incref.unadj <- 
  module.incident.ref.unadj %>% 
  dplyr::mutate(Color = substring(term, 3, 100)) %>%
  dplyr::select(Color, desc, hazr, pval, Name, hubs, freq)

plot.module.incpef.unadj <- 
  module.incident.pef.unadj %>% 
  dplyr::mutate(Color = substring(term, 3, 100)) %>%
  dplyr::select(Color, desc, hazr, pval, Name, hubs, freq)

```
```{r}

df1 <- eigenGenes$ME$eigengenes
df2 <- eigenGenes$ME$averageExpr
df3 <- eigenGenes$ME$varExplained
names(df3) <- names(eigenGenes$ME$eigengenes)

df4 <- eigenData.V31$ME$eigengenes
df5 <- eigenData.V31$ME$averageExpr
df6 <- eigenData.V31$ME$varExplained
names(df6) <- names(eigenData.V31$ME$eigengenes)

df7 <- tibble::tibble(term = labels$term, Module = eigenGenes$mergedColors) %>%
    dplyr::group_by(Module) %>%
    dplyr::mutate(place = 1:length(term)) %>%
    tidyr::pivot_wider(names_from = place, values_from = term, values_fill = "") %>%
    as.data.frame() %>% t()

df8 <- tibble::tibble(term = labels$name, Module = eigenGenes$mergedColors) %>%
    dplyr::group_by(Module) %>%
    dplyr::mutate(place = 1:length(term)) %>%
    tidyr::pivot_wider(names_from = place, values_from = term, values_fill = "") %>%
    as.data.frame() %>% t()

df9 <- tibble::tibble(term = labels$gene, Module = eigenGenes$mergedColors) %>%
    dplyr::group_by(Module) %>%
    dplyr::mutate(place = 1:length(term)) %>%
    tidyr::pivot_wider(names_from = place, values_from = term, values_fill = "") %>%
    as.data.frame() %>% t()

write.csv(df1, '~/Desktop/visit-five-eigengenes.csv', row.names = FALSE)
write.csv(df2, '~/Desktop/visit-five-average-exprs.csv', row.names = FALSE)
write.csv(df3, '~/Desktop/visit-five-var-explained.csv', row.names = FALSE)
write.csv(df4, '~/Desktop/visit-three-eigengenes.csv', row.names = FALSE)
write.csv(df5, '~/Desktop/visit-three-average-exprs.csv', row.names = FALSE)
write.csv(df6, '~/Desktop/visit-three-var-explained.csv', row.names = FALSE)
write.csv(df7, '~/Desktop/proteins-modules-seqs.csv', row.names = FALSE)
write.csv(df8, '~/Desktop/proteins-modules-names.csv', row.names = FALSE)
write.csv(df9, '~/Desktop/proteins-modules-genes.csv', row.names = FALSE)



```

```{r}
library(xlsx)

wb <- createWorkbook()
sheet1   <- createSheet(wb, sheetName = 'Module Summaries')
sheet2   <- createSheet(wb, sheetName = 'Incident HF Adjusted')
sheet2a  <- createSheet(wb, sheetName = 'V3 Incident HF Adjusted')
sheet3   <- createSheet(wb, sheetName = 'Incident rEF Adjusted')
sheet4   <- createSheet(wb, sheetName = 'Incident pEF Adjusted')
sheet5   <- createSheet(wb, sheetName = 'Incident HF No Adjustment')
sheet5a  <- createSheet(wb, sheetName = 'V3 Incident HF No Adjustment')
sheet6   <- createSheet(wb, sheetName = 'Incident rEF No Adjustment')
sheet7   <- createSheet(wb, sheetName = 'Incident pEF No Adjustment')


addDataFrame(mod.summary %>% as.data.frame(), sheet = sheet1, row.names = FALSE)
addDataFrame(plot.module.inchf.adj  %>% as.data.frame(), sheet = sheet2, row.names = FALSE)
addDataFrame(plot.module.inchf.V3.adj  %>% as.data.frame(), sheet = sheet2a, row.names = FALSE)
addDataFrame(plot.module.incref.adj %>% as.data.frame(), sheet = sheet3, row.names = FALSE)
addDataFrame(plot.module.incpef.adj %>% as.data.frame(), sheet = sheet4, row.names = FALSE)

addDataFrame(plot.module.inchf.unadj  %>% as.data.frame(), sheet = sheet5, row.names = FALSE)
addDataFrame(plot.module.inchf.V3.unadj  %>% as.data.frame(), sheet = sheet5a, row.names = FALSE)
addDataFrame(plot.module.incref.unadj %>% as.data.frame(), sheet = sheet6, row.names = FALSE)
addDataFrame(plot.module.incpef.unadj %>% as.data.frame(), sheet = sheet7, row.names = FALSE)

plot.mod.inchf.adj   <- plot.module.inchf.adj  %>%  
  dplyr::mutate(Name = Color) %>%
  volcanoPlot.temp.refpef(4877, 1)

plot.mod.inchf.V3.adj   <- plot.module.inchf.V3.adj  %>%  
  dplyr::mutate(Name = Color) %>%
  volcanoPlot.temp.refpef(4877, 1)

plot.mod.incref.adj   <- plot.module.incref.adj %>% 
  dplyr::mutate(Name = Color) %>% 
  volcanoPlot.temp.refpef(4877, 1)

plot.mod.incpef.adj   <- plot.module.incpef.adj %>%
  dplyr::mutate(Name = Color) %>%
  volcanoPlot.temp.refpef(4877, 1)

plot.mod.inchf.unadj   <- plot.module.inchf.unadj %>% 
  dplyr::mutate(Name = Color) %>%
  volcanoPlot.temp.refpef(4877, 1)

plot.mod.inchf.V3.unadj   <- plot.module.inchf.V3.unadj %>% 
  dplyr::mutate(Name = Color) %>%
  volcanoPlot.temp.refpef(4877, 1)

plot.mod.incref.unadj   <- plot.module.incref.unadj %>% 
  dplyr::mutate(Name = Color) %>% 
  volcanoPlot.temp.refpef(4877, 1)

plot.mod.incpef.unadj   <- plot.module.incpef.unadj %>% 
  dplyr::mutate(Name = Color) %>% 
  volcanoPlot.temp.refpef(4877, 1)


ggsave(    'volcano-inchf-adj.png', plot.mod.inchf.adj)
addPicture('volcano-inchf-adj.png', sheet = sheet2, scale = 0.4)

ggsave(    'volcano-inchf-V3-adj.png', plot.mod.inchf.V3.adj)
addPicture('volcano-inchf-V3-adj.png', sheet = sheet2a, scale = 0.4)

ggsave(    'volcano-incref-adj.png', plot.mod.incref.adj)
addPicture('volcano-incref-adj.png', sheet = sheet3, scale = 0.4)

ggsave(    'volcano-incpef-adj.png', plot.mod.incpef.adj)
addPicture('volcano-incpef-adj.png', sheet = sheet4, scale = 0.4)

ggsave(    'volcano-inchf-unadj.png', plot.mod.inchf.unadj)
addPicture('volcano-inchf-unadj.png', sheet = sheet5, scale = 0.4)

ggsave(    'volcano-inchf-V3-unadj.png', plot.mod.inchf.V3.unadj)
addPicture('volcano-inchf-V3-unadj.png', sheet = sheet5a, scale = 0.4)

ggsave(    'volcano-incref-unadj.png', plot.mod.incref.unadj)
addPicture('volcano-incref-unadj.png', sheet = sheet6, scale = 0.4)

ggsave(    'volcano-incpef-unadj.png', plot.mod.incpef.unadj)
addPicture('volcano-incpef-unadj.png', sheet = sheet7, scale = 0.4)

xlsx <- '~/Desktop/module-associations.xlsx'
saveWorkbook(wb, file = xlsx)


```


```{r echo.as.outcome, eval=FALSE, echo=TRUE, message=FALSE, warning=FALSE}

echo.vars <- readr::read_csv(echov.mods)[[1]][c(-1, -2)]
adtl.vars <- readr::read_csv(addtl.mods)[[1]][c(-1)]

fifth.visit.adtl <- 
  add.data(new.path = addtl.vars, 
           old.data = fifth.visit,
           mods = addtl.mods)

fifth.visit.echo <- 
  add.data(new.path = study.path,
           old.data = fifth.visit.adtl,
           mods = echov.mods) 

num.var.adtl <- 
  numeric.id(fifth.visit.echo,
             c(echo.vars, 
               adtl.vars))

fifth.visit.echo.scaled <- 
  get.scaled(fifth.visit.echo, 
             num.var.adtl)

univariate.echo.models <- 
  lin.arry.aggr(proteins,
                fifth.visit.echo.scaled,
                echo.vars, adjust, labels) 

numeric.echo.regression <- 
  univariate.echo.models$numeric

table.echo.regression <- 
  univariate.echo.models$character 

univariate.echo.terms.bonf <- 
  lin.reg.terms.to.keep(univariate.echo.models$all.res, 4877)

```

```{r}

univariate.echo.models.unscaled.alladj <- 
  lin.arry.aggr(proteins,
                fifth.visit.echo,
                echo.vars, adjust, labels) 

univariate.echo.models.unscaled.minadj <- 
  lin.arry.aggr(proteins,
                fifth.visit.echo,
                echo.vars, c("age", "race", "sex"), labels) 

univariate.echo.models.scaled.minadj <- 
  lin.arry.aggr(proteins,
                fifth.visit.echo.scaled,
                echo.vars, c("age", "race", "sex"), labels) 


uni.echo.terms.bonf.unscaled.all <- 
  lin.reg.terms.to.keep(univariate.echo.models.unscaled.alladj$all.res, 4877)

uni.echo.terms.bonf.unscaled.min <- 
  lin.reg.terms.to.keep(univariate.echo.models.unscaled.minadj, 4877)

uni.echo.terms.bonf.scaled.all <- 
  lin.reg.terms.to.keep(univariate.echo.models, 4877)

uni.echo.terms.bonf.scaled.min <- 
  lin.reg.terms.to.keep(univariate.echo.models.scaled.minadj, 4877)

```

```{r}
min.adj <- c("race", "sex", "age")

echo.enet.unscaled.all <- 
  linear.elastic.net.array(fifth.visit.echo, adjust,
                           uni.echo.terms.bonf.unscaled.all) %>%
  linear.get.score.enet.temp(fifth.visit.echo, adjust)

echo.enet.unscaled.min<- 
  linear.elastic.net.array(fifth.visit.echo, min.adj,
                           uni.echo.terms.bonf.unscaled.min) %>%
  linear.get.score.enet.temp(fifth.visit.echo, min.adj)

echo.enet.scaled.min <- 
  linear.elastic.net.array(fifth.visit.echo.scaled, min.adj,
                           uni.echo.terms.bonf.scaled.min) %>%
  linear.get.score.enet.temp(fifth.visit.echo.scaled, min.adj)

echo.enet.scaled.all <- 
  linear.elastic.net.array(fifth.visit.echo.scaled, adjust,
                           uni.echo.terms.bonf.scaled.all) %>%
  linear.get.score.enet.temp(fifth.visit.echo.scaled, adjust)
```



```{r}

univ.echo.models.genes <-
  dplyr::bind_cols(fifth.visit.echo.scaled, 
                   eigenData %>% dplyr::select(-all_of(c(adjust, time, outc, "hfref", "hfpef"))))

dyn.colors <- names(eigenData %>% dplyr::select(-all_of(c(adjust, time, outc, "hfref", "hfpef"))))
module.lin.arr <- lin.arry.aggr(dyn.colors, univ.echo.models.genes, echo.vars, adjust, labels)

echo.heatmap <- module.lin.arr$numeric %>% dplyr::select(term, dplyr::ends_with("estm")) %>%
  tibble::column_to_rownames("term") %>% data.matrix()
```


```{r top.candidates.echo.outcomes, cache=TRUE}

top.candidates.echos <- 
  univariate.echo.terms.bonf$candidates %>% 
  purrr::flatten_chr() %>% 
  table() %>% 
  sort(decreasing = TRUE)

top.candidates.echos.names <-
  top.candidates.echos

names(top.candidates.echos.names) <- 
  labels[names(top.candidates.echos), "name"] %>%
  substr(1, 40)

full.cands <- 
  names(top.candidates.echos)[which(top.candidates.echos > 4)]
```

```{r echo.elastic.nets, cache=TRUE}

echo.elastic.nets <- 
  linear.elastic.net.array(fifth.visit.echo.scaled, adjust,
                           univariate.echo.terms.bonf) %>%
  linear.get.score.enet(fifth.visit.echo.scaled, adjust)


```


```{r echo.random.forests, cache=TRUE}

echo.randomforests <- 
  linear.filter.rf.array(fifth.visit.echo.scaled,
                         echo.vars, 30, adjust)

```
